image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.7.1"

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
# minimal resource requests and limits are set to minimize strain on local machine 
# while allowing necessary resources for the application to run
# and for policies to be tested effectively.

service:
  port: 9898

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
