apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-api
  namespace: widget-api
  labels:
    app: widget-api
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: widget-api
  template:
    metadata:
      labels:
        app: widget-api
    spec:
      serviceAccountName: widget-api
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: widget-api
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
