apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: widget-api-egress
  namespace: widget-api
spec:
  podSelector:
    matchLabels:
      app: widget-api
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
