apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: widget-api
  namespace: widget-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: widget-api
  namespaceSelector:
    matchNames:
      - widget-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s