apiVersion: v1
kind: Service
metadata:
  name: widget-api
  namespace: widget-api
  labels:
    app: widget-api
spec:
  selector:
    app: widget-api
  ports:
    - name: http
      port: 9898
      targetPort: http