apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: allow-approved-registries
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - widget-api
      validate:
        message: "Images must come from approved registries."
        foreach:
          - list: "request.object.spec.containers"
            pattern:
              image: "ghcr.io/*"